<%@ Page Language="C#" MasterPageFile="~/Admin/Admin.Master" AutoEventWireup="true"
    CodeBehind="view_enquiry_page.aspx.cs" Inherits="Master_MLM.Admin.view_enquiry_page"
    Title="View Enquiry" EnableEventValidation="false" %>

<asp:Content ID="Content1" ContentPlaceHolderID="title" runat="server">
    View Enquiry
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .ddsmoothmenu ul li a.eleven {
            color: #446CB3;
            background: #fff;
            text-shadow: none;
            box-shadow: none;
            border-right: 1px solid #446CB3;
            cursor: pointer;
        }


        @media print {
            .noPrint {
                display: none;
            }
        }
    </style>
    <script type="text/javascript">
        function printTable2() {
            var printContent = document.getElementById("enquiry");
            var windowUrl = 'abount:blank';
            var num;
            var uniqueName = new Date();
            var windowName = 'Print' + uniqueName.getTime();
            var printWindow = window.open(num, windowName, 'left=50000,top=50000,width=0,height=0');
            printWindow.document.write(printContent.innerHTML);
            printWindow.document.close();
            printWindow.focus();
            printWindow.print();
            printWindow.close();
        }
    </script>


</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div id="content">

        <div id="content-header">
            <div id="breadcrumb">
                <a href="/" title="Go to Home" class="tip-bottom"><i class="icon-home"></i>Home</a>
                <a href="#" class="current">Website</a>
                <a href="#" class="current">View Enquiry</a>
            </div>
        </div>

        <div class="container-fluid minimum-height">
            <div class="row-fluid">
                <div class="widget-box">
                    <div class="widget-title bg_lg">
                        <span class="icon"><i class="icon-signal"></i></span>
                        <span class="icon-right"><i class="icon-print" onclick="$('#<%=LinkButton1.ClientID %>').click();"></i></span>
                        <span class="icon-right"><i class="icon-save" onclick="$('#<%=img_expord.ClientID %>').click();"></i></span>
                        <h5>View Enquiry</h5>
                    </div>
                    <div class="widget-content">
                        <div style="display: none;">
                            <asp:LinkButton ID="LinkButton1" OnClientClick="printTable2();" runat="server">
                                    <img src="../images/printer.png" height="25" width="25" border="0" alt="" /></asp:LinkButton>
                            <asp:ImageButton ID="img_expord" runat="server" Height="32px" ImageUrl="~/images/Excelicons.png"
                                Style="margin-left: 20px" OnClick="img_expord_Click" />
                        </div>
                        <div class="row-fluid" id="enquiry">
                            <asp:Panel ID="pnl_manage_request" runat="server">
                                <asp:GridView ID="grd_view_enquiry" runat="server" Style="margin: 21px auto 2px 0px; text-align: center; font-weight: normal; height: auto; float: left;"
                                    Width="1120px"
                                    AllowPaging="True" OnPageIndexChanging="grd_view_enquiry_PageIndexChanging" AutoGenerateColumns="False"
                                    AutoGenerateDeleteButton="True" OnRowDeleting="grd_view_enquiry_RowDeleting"
                                    PageSize="20">
                                    <PagerSettings FirstPageText="" LastPageText="" NextPageText="" />
                                    <PagerStyle HorizontalAlign="Right" Wrap="False" CssClass="noPrint gridview1" />
                                    <Columns>
                                        <asp:TemplateField HeaderText="Purpose">
                                            <ItemTemplate>
                                                <asp:Label ID="lbl_purpose" runat="server" Text='<%#Bind("purpose") %>'>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Name">
                                            <ItemTemplate>
                                                <asp:Label ID="lbl_name" runat="server" Text='<%#Bind("name") %>'>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="E-Mail">
                                            <ItemTemplate>
                                                <asp:Label ID="lbl_email" runat="server" Text='<%#Bind("email") %>'>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Contact No.">
                                            <ItemTemplate>
                                                <asp:Label ID="lbl_contact_no" runat="server" Text='<%#Bind("mobile") %>'>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Message">
                                            <ItemTemplate>
                                                <asp:Label ID="lbl_message" runat="server" Text='<%#Bind("message") %>'>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Date">
                                            <ItemTemplate>
                                                <asp:Label ID="lbl_date" runat="server" Text='<%#Bind("date") %>'>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText=" ID" Visible="false">
                                            <ItemTemplate>
                                                <asp:Label ID="lbl_id" runat="server" Text='<%#Bind("id") %>'>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                    </Columns>
                                    <HeaderStyle BackColor="#1C6577" BorderColor="#1C6577" BorderStyle="Solid" BorderWidth="2px"
                                        Font-Names="Verdana" ForeColor="White" />
                                </asp:GridView>
                            </asp:Panel>
                            <div class="span12" style="text-align: center;">
                                <asp:Label ID="lbl_message" runat="server" CssClass="label label-warning"></asp:Label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <iframe name="print_frame" width="0" height="0" frameborder="0" src="about:blank"></iframe>
</asp:Content>
